---
- name: "Create /etc/zabbix/externalscripts"
  file:
    path: "/etc/zabbix/externalscripts"
    state: directory
    owner: root
    group: zabbix
    mode: 0750

- name: "Install externalscripts"
  copy:
    src: "{{ item }}"
    dest: "/etc/zabbix/externalscripts/{{ item }}"
    owner: root
    group: zabbix
    mode: 0750
  with_items:
  - "sslnotafter.rb"
