---
- name: "Install frontend packages"
  apt: name={{ item }}
  with_items: "{{ zabbix_frontend_packages }}"

- lineinfile:
    dest: /etc/nginx/sites-available/default
    insertbefore: "^}$"
    line: "	include /usr/share/doc/zabbix-frontend-php/examples/nginx.conf;"
  notify: restart nginx
- template: src=php-local.ini.j2 dest=/etc/php/7.0/fpm/conf.d/50-local.ini owner=root group=root mode=0644
  notify: restart php-fpm
- template: src=zabbix.conf.php.j2 dest=/etc/zabbix/zabbix.conf.php owner=root group=www-data mode=0640
  notify:
  - restart php-fpm

- name: "Overwrite font symlink"
  file:
    dest: /usr/share/zabbix/fonts/DejaVuSans.ttf
    src: "{{ zabbix_frontend_font_path }}"
    state: link
