---
- include: packages.yml tags=zabbix-packages
- include: postgres.yml tags=zabbix-postgres
  sudo: yes
  sudo_user: postgres
- include: server.yml tags=zabbix-server
- include: frontend.yml tags=zabbix-frontend
