---
- include: packages.yml tags=zabbix-packages
- include: postgres.yml tags=zabbix-postgres
  become: yes
  become_user: postgres
- include: backup.yml tags=zabbix-backup
- include: server.yml tags=zabbix-server
- include: frontend.yml tags=zabbix-frontend
- include: externalscripts.yml tags=zabbix-externalscripts
