---
- include: packages.yml tags=zabbix-packages
- include: postgres.yml tags=zabbix-postgres
  become: yes
  become_user: postgres
- include: postgres-backup.yml tags=zabbix-postgres-backup
- include: server.yml tags=zabbix-server
- include: frontend.yml tags=zabbix-frontend
