---
- include: packages.yml tags=zabbix-packages
- include: postgres.yml tags=zabbix-postgres
  sudo: yes
  sudo_user: postgres
- include: postgres-backup.yml tags=zabbix-postgres-backup
- include: server.yml tags=zabbix-server
- include: frontend.yml tags=zabbix-frontend
- include: server-config.yml tags=zabbix-server-config
