---
- name: restart nginx
  service: name=nginx state=restarted
- name: restart php5-fpm
  service: name=php5-fpm state=restarted
- name: restart postgresql
  service: name=postgresql state=restarted
- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted
- name: restart zabbix-server
  service: name=zabbix-server state=restarted
